# ========================================================
# planner_server: global path planner
# ========================================================
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_theta_star_planner::ThetaStarPlanner" 
      how_many_corners: 8 #8
      w_euc_cost: 1.0
      w_traversal_cost: 8. #2.0

smoother_server:
  ros__parameters:
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    robot_base_frame: base_footprint
    transform_tolerance: 0.4
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      do_refinement: True
      refinement_num: 2
      max_its: 1000
      w_data: 0.2
      w_smooth: 0.3
      enforce_path_inversion: True

# ========================================================
# controller_server:= trajectory follower
# ========================================================
controller_server:
  ros__parameters:
    controller_frequency: 30. #20.
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.02
    min_y_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.05
    failure_tolerance: 0.3
    odom_topic: "odom_ekf"
    odom_duration: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      # plugin: "nav2_controller::SimpleProgressChecker"
      plugin: "nav2_controller::PoseProgressChecker"
      required_movement_radius: 0.10
      required_movement_angle: 0.5
      movement_time_allowance: 12.0

    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1 #0.2
      yaw_goal_tolerance: 0.2 #0.2


    # DWB CONTROLLER
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: -0.7
      min_vel_y: -0.7
      max_vel_x: 0.7
      max_vel_y: 0.7
      max_vel_theta: 1.5
      min_speed_xy: 0.
      max_speed_xy: 0.7
      min_speed_theta: 0.0
      acc_lim_x: 2.0
      acc_lim_y: 2.0
      acc_lim_theta: 3.0
      decel_lim_x: -2.0
      decel_lim_y: -2.0
      decel_lim_theta: -3.0
      vx_samples: 10
      vy_samples: 10 #1
      vtheta_samples: 10
      sim_time: .4 #0.8 #1.7
      linear_granularity: 0.02 # 0.05
      angular_granularity: 0.02 # 0.025
      transform_tolerance: 0.4
      xy_goal_tolerance: 0.1 #0.2
      trans_stopped_velocity: 0.05
      short_circuit_trajectory_evaluation: True
      limit_vel_cmd_in_traj: False
      stateful: True
      critics: ["BaseObstacle", "GoalAlign", "GoalDist", "Oscillation", "PathAlign", "PathDist", "PreferForward", "RotateToGoal", "Twirling"]

      BaseObstacle:
        scale: 0.
      
      GoalAlign:
        scale: 0. #0. 
        forward_point_distance: .5

      PathAlign: 
        scale: 0.
        forward_point_distance: .5

      PreferForward:
        scale: 0.
      
      GoalDist:
        scale: 1.
      
      Oscillation:
        scale: 1.
      
      PathDist:
        scale: 2. #0.5
      
      RotateToGoal:
        scale: 5. #5.
        slowing_factor: 1.0
        lookahead_time: 1.0
        xy_goal_tolerance: 0.1 #0.2
      
      Twirling: 
        scale: 1. # 1.0

# ========================================================
# part of controller_server and planner_server
# ========================================================
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 2
      height: 2
      resolution: 0.05
      robot_radius: 0.3
      # plugins: ["voxel_layer", "inflation_layer"]
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        enabled: true
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.2
      obstacle_layer:
        enabled: true
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      robot_radius: 0.3
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.4
      always_send_full_costmap: True

# ========================================================
# bt_navigator: Behaviour Tree - decision-making brain of Nav2
# ========================================================
bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: odom_ekf
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code


# ========================================================
# behavior_server - Recovery and auxiliary actions
# ========================================================
behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    # behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    # behavior_plugins: ["spin", "backup", "assisted_teleop", "wait"]
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    # drive_on_heading:
    #   plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    # assisted_teleop:
    #   plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2


# ========================================================
# waypoint_follower - not used currently
# ========================================================
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

