# twist_mux:
#   ros__parameters:
#     topics:
#       navigation:
#         topic   : /cmd_vel
#         timeout : 0.5
#         priority: 10
#       keyboard:
#         topic   : /cmd_vel_keyboard
#         timeout : 0.5
#         priority: 100

twist_mux_node: 
  ros__parameters: 
    use_stamped: true 
    # cmd_vel: /rmitbot_controller/cmd_vel # Output topic for velocity commands 
    cmd_vel: cmd_vel # Output topic for velocity commands 
    topics: 
      # joy: 
      #   topic: /cmd_vel_joystick # Input topic for joystick commands 
      #   priority: 10 
      #   timeout: 0.5 
      keyboard: 
        topic: cmd_vel_keyboard # Input topic for keyboard commands 
        priority: 20 
        timeout: 0.5 
      navigation: 
        topic: cmd_vel_navigation # Input topic for navigation commands 
        priority: 5 
        timeout: 0.5 